/**
 * Code for partners table creation
 * @author Lief Esbenshade
 */

CREATE TABLE partners (
  uuid VARCHAR(255) NOT NULL REFERENCES users (uuid) ON DELETE CASCADE, 
  partner_uuid VARCHAR(255) NOT NULL REFERENCES users (uuid) ON DELETE CASCADE, 
  proposer BOOLEAN NOT NULL,
  pair_propose_date TIMESTAMP NOT NULL,
  pair_confirm_date TIMESTAMP,
  confirmed BOOLEAN NOT NULL,
  UNIQUE(uuid, partner_uuid, proposer) 
);
